### ISSUE TITLE
TypeError generated for markdown files with tables

### ISSUE THREAD

**Issue by ryancheley** [simonw/markdown-to-sqlite#2]
There may be other instances where this `TypeError` failure occurs, but the markdown attached ([its-science.md](https://github.com/simonw/markdown-to-sqlite/files/6793063/its-science.md)) will generate the following error:

```
Traceback (most recent call last):
  File "/Users/ryan/Documents/ryancheley.com/venv/bin/markdown-to-sqlite", line 8, in <module>
    sys.exit(cli())
  File "/Users/ryan/Documents/ryancheley.com/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ryan/Documents/ryancheley.com/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/ryan/Documents/ryancheley.com/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ryan/Documents/ryancheley.com/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ryan/Documents/ryancheley.com/venv/lib/python3.9/site-packages/markdown_to_sqlite/cli.py", line 27, in cli
    doc = {
TypeError: 'str' object is not a mapping
```

**Comment by ryancheley** [comment]
A potential patch has been written [here](https://github.com/ryancheley/markdown-to-sqlite/tree/ryancheley-patch-1) but I still need to write tests
